input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.3.1.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://host.docker.internal:5432/meta_db"
    jdbc_user => "postgres"
    jdbc_password => "postgres"
    statement => "SELECT tp.*, COUNT(distinct r.id) AS review_count, AVG(distinct r.rating) AS rating_average FROM tour_post tp LEFT JOIN review r ON tp.content_id = r.tour_post_content_id WHERE tp.content_id > :sql_last_value GROUP BY tp.content_id ORDER BY tp.content_id ASC;"
    schedule => "*/1 * * * *"
    sql_log_level => "debug"
    tracking_column => "content_id"
    use_column_value => true
    record_last_run => true
    last_run_metadata_path => "/usr/share/logstash/tourpost_last_run_metadata"
  }
}
filter {
  mutate {
    convert => {"%{mapy}" => "float"}
    convert => {"%{mapx}" => "float"}
    convert => { "rating_average" => "float" }
  }
  mutate {
    add_field => { "[location][lat]" => "%{mapy}" }
    add_field => { "[location][lon]" => "%{mapx}" }
  }
  mutate {
    remove_field => ["@version", "jdbc_connection_string", "jdbc_user", "jdbc_password", "mapx", "mapy","sigungucode", "homepage", "cpyrht_div_cd"]
  }
  mutate {
    convert => {"[location][lat]" => "float"}
    convert => {"[location][lon]" => "float"}
  }
    ruby{
      code => "
        event.set('[location]', { 'lat' => event.get('[location][lat]'), 'lon' => event.get('[location][lon]') })
        event.set('rating_average', (event.get('rating_average') * 10).floor / 10.0)
      "
    }
}
output {
if [language] == "KorService1"{
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourpostkor"
    document_id => "%{content_id}"
    manage_template => true
    template_name => "tourpostkortemplate"
    template => "/usr/share/logstash/template/TourPostKoreanTemplate.json"
    template_overwrite => true
  }
}
if [language] == "JpnService1"{
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourpostjpn"
    document_id => "%{content_id}"
    manage_template => true
    template_name => "tourpostjpntemplate"
    template => "/usr/share/logstash/template/TourPostJapaneseTemplate.json"
    template_overwrite => true
  }
}
if [language] == "EngService1"{
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourposteng"
    document_id => "%{content_id}"
    manage_template => true
    template_name => "tourpostengtemplate"
    template => "/usr/share/logstash/template/TourPostEnglishTemplate.json"
    template_overwrite => true
  }
}
if [language] == "ChsService1"{
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourpostchs"
    document_id => "%{content_id}"
    manage_template => true
    template_name => "tourpostchstemplate"
    template => "/usr/share/logstash/template/TourPostChineseTemplate.json"
    template_overwrite => true
  }
}
  stdout {
    codec => rubydebug { metadata => true }
  }
}