apis:
  api:          # 한국관광공사_국문 관광정보 서비스 OPEN API
    service-key: 2%2BfyNjjntQ7C7SDTU4YsECf%2FYAvnhnKGgiy0L2MpMgAdA28xoosjB%2FlwcF3goU5%2BP8LKoFs4JH2YlQePYeLnrA%3D%3D
schedule:
  use: true # 스케줄러 활성화 여부
  # cron: "0 0/5 * * * ?" # 매 5분마다 실행
  # cron: "/3 * * * * ?" # 3초마다
  # cron: "0 * * * * *" # 매 분마다
  # cron: "0 0 0 * * ?"  # 0시 0분 0초 마다(24시정각)
  cron_for_apis: "0 0 5 * * *"    # 스케쥴러
  # 공공 데이터 포털 https://www.data.go.kr api 일일 최대 요청 횟수
  # 개발계정: 하루 평균 1,000건의 요청이 가능합니다.
  # 운영계정: 하루 최대 100,000건의 요청이 허용됩니다.

custom:
  jwt:
    secretKey: lDTnvgXK8FVtN2kufiFr+3IH1sYnbn74Utejna5VLsElrmT1cysi+/z8AK94E5fHiilIlegehcEPpb5EX4RtNw==
