spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true      # SQL 쿼리 로깅 (개발 중에만 true)
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.web: DEBUG
    team.klover: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

