spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_db
    username: postgres  # docker-compose.yml의 POSTGRES_USER와 동일하게 설정
    password: postgres # docker-compose.yml의 POSTGRES_PASSWORD와 동일하게 설정
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update로 설정 (운영 환경에서는 validate 또는 none)
    show-sql: true      # SQL 쿼리 로깅 (개발 중에만 true)
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.springframework.web: DEBUG
    team.klover: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE