spring:
  datasource:
    url: jdbc:postgresql://43.203.244.12:5432/meta_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      uri: mongodb://admin:admin@43.203.244.12:27017/meta_db?authSource=admin
      database: meta_db
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: 13.125.235.125
    port: 5672
    username: admin
    password: admin

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    team.klover: DEBUG  # 내 애플리케이션 패키지는 DEBUG 유지 가능
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log
  logback:
    rolling policy:
      file-name-pattern: logs/app-%d{yyyy-MM-dd}.log
      max-history: 7
      total-size-cap: 100MB

es:
  host: "es.tmdgjsdl1.site"