spring:
  datasource:
    url: jdbc:postgresql://43.203.244.12:5432/meta_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false      # 운영 환경에서는 보통 false로 설정
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://admin:admin@43.203.244.12:27017/meta_db?authSource=admin
      database: meta_db
  rabbitmq:
    host: 13.125.235.125
    port: 5672
    username: admin
    password: admin

# Swagger 비활성화 (운영 환경에서는 보통 사용 안 함)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.springframework.web: INFO
    team.klover: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: ERROR

es:
  host: "es.tmdgjsdl1.site"