server:
  port: 8090
spring:
  application:
    name: server
  profiles:
    active: dev
    include: secret
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true