input {
  rabbitmq {
    host => "host.docker.internal"
    port => 5672
    queue => "ES_COMMPOST_UPDATE"
    user => "admin"
    password => "admin"
    durable => true
    codec => json
  }
}
output {
    if [language] == "KO"{
        elasticsearch {
            hosts => ["elasticsearch:9200"]
            index => "commpostkor"
            action => "update"
            document_id => "%{id}"
        }
    }
    if [language] == "EN"{
        elasticsearch {
            hosts => ["elasticsearch:9200"]
            index => "commposteng"
            action => "update"
            document_id => "%{id}"
        }
    }
    if [language] == "JA"{
        elasticsearch {
            hosts => ["elasticsearch:9200"]
            index => "commpostchs"
            action => "update"
            document_id => "%{id}"
        }
    }
    if [language] == "ZH"{
        elasticsearch {
            hosts => ["elasticsearch:9200"]
            index => "commpostchs"
            action => "update"
            document_id => "%{id}"
        }
    }
}