input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.3.1.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://host.docker.internal:5432/meta_db"
    jdbc_user => "postgres"
    jdbc_password => "postgres"
    statement => "select tp.content_id, tp.'language' ,coalesce(count(distinct r.id),0) as review_count, coalesce(avg(distinct r.rating),0) as rating_average from review_tour_post rtp join review r on r.id = rtp.review_id join tour_post tp on rtp.tour_post_id = tp.content_id group by tp.common_place_id, tp.content_id"
    schedule => "*/2 * * * *"
    sql_log_level => "debug"
  }
}
filter {
  mutate {
    remove_field => ["@version", "jdbc_connection_string", "jdbc_user", "jdbc_password"]
  }
    mutate {
      convert => { "rating_average" => "float" }
    }
    ruby {
      code => "event.set('rating_average', (event.get('rating_average') * 10).floor / 10.0)"
    }
}
output {
if [language] == "KorService1"{
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourpostkor"
    document_id => "%{content_id}"
    action => "update"
  }
}
if [language] == "ChsService1"{
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourpostchs"
    document_id => "%{content_id}"
    action => "update"
  }
}
if [language] == "JpnService1"{
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourpostjpn"
    document_id => "%{content_id}"
    action => "update"
  }
}
if [language] == "EngService1"{
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourposteng"
    document_id => "%{content_id}"
    action => "update"
  }
}
  stdout {
    codec => rubydebug { metadata => true }
  }
}