input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql-42.3.1.jar"
    jdbc_driver_class => "org.postgresql.Driver"
    jdbc_connection_string => "jdbc:postgresql://host.docker.internal:5432/meta_db"
    jdbc_user => "postgres"
    jdbc_password => "postgres"
    statement => "select tp.content_id, count(distinct r.id) as review_count, avg(distinct r.rating) as rating_average from tour_post tp left join review r on tp.content_id = r.tour_post_content_id where tp.language = 'EngService1' group by tp.content_id"
    schedule => "*/2 * * * *"
    sql_log_level => "debug"
  }
}
filter {
  mutate {
    remove_field => ["@version", "jdbc_connection_string", "jdbc_user", "jdbc_password"]
  }
}
output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "tourposteng"
    document_id => "%{content_id}"
    action => "update"
  }
  stdout {
    codec => rubydebug { metadata => true }
  }
}